# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82543f456e7c9bb61d610e2371fc240c7b47850570bef18b899198f25cad649db182c87a9c1c6899b1022faf365114d1fad2e1554954fb5d5ced56b0ec59387a

test:
  secret_key_base: 5870251f88bea91f9e2350c3bccd16528d2f4f64ad0b6f3076962e32198922e7074370a3cbfefd4f03ca13f25679b555e9eceb0c2107d9272b3c9739ce80867e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
